//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.06 at 07:49:26 AM CET 
//


package de.mtg.tr03124;

import java.util.ArrayList;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * This type describes formatted text. Only formatting text elements are allowed, no plain text content.
 * 
 * <p>Java class for FormattedText complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FormattedText">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;group ref="{http://bsi.bund.de/TR03124}FormattedTextGroup" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FormattedText", propOrder = {
    "headingOrParagraphOrEnumeration"
})
public class FormattedText {

    @XmlElements({
        @XmlElement(name = "Heading", type = Heading.class),
        @XmlElement(name = "Paragraph", type = Hypertext.class),
        @XmlElement(name = "Enumeration", type = Enumeration.class),
        @XmlElement(name = "List", type = de.mtg.tr03124.List.class)
    })
    protected java.util.List<Object> headingOrParagraphOrEnumeration;

    /**
     * Gets the value of the headingOrParagraphOrEnumeration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the headingOrParagraphOrEnumeration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHeadingOrParagraphOrEnumeration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Heading }
     * {@link Hypertext }
     * {@link Enumeration }
     * {@link de.mtg.tr03124.List }
     * 
     * 
     */
    public java.util.List<Object> getHeadingOrParagraphOrEnumeration() {
        if (headingOrParagraphOrEnumeration == null) {
            headingOrParagraphOrEnumeration = new ArrayList<Object>();
        }
        return this.headingOrParagraphOrEnumeration;
    }

}
