//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.06 at 07:49:26 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bsi.bund.de/TR03124", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.mtg.tr03124;
